sudo: false
language: c
os:
  - linux
  - osx
dist: trusty

before_script:
  - set -e
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..
  - sed -i -e 's,cc = gcc,cc = clang,' config/nim.cfg
  - export PATH=$(pwd)/bin:$PATH
  - git clone --depth 1 https://github.com/nim-lang/Nim.git
  - cd Nim
  - nim c -d:release koch
  - ./koch boot -d:release
script:
  - nim e build.nims
  