sudo: false
language: c
os:
  - linux
  - osx
dist: trusty

before_script:
  - set -e
  - git clone --depth 1 https://github.com/nim-lang/csources.git
  - cd csources
  - sh build.sh
  - cd ..    
  - git clone --depth 1 https://github.com/nim-lang/Nim.git
  - mv $(pwd)/csources/bin/nim $(pwd)/Nim/bin/
  - cd Nim
  - sed -i -e 's,cc = gcc,cc = clang,' config/nim.cfg
  - export PATH=$(pwd)/bin:$PATH
  - nim c -d:release koch
  - ./koch boot -d:release  
  - cd ..
script:
  - nim e build.nims
  