packageName   = "nimAGG"
version       = "0.1.2"
author        = "Andri Lim"
description   = "nimAGG is a Nim port of Anti Grain Geometry(AGG)"
license       = "MIT"

requires: "nim >= 0.18.1"
requires: "sdl2_nim#head"
requires: "nimBMP >= 0.1.0"
requires: "freetype >= 0.1.0"
requires: "polyBool >= 0.1.0"
requires: "opengl >= 0.1.0"
