ren agg_alpha_mask_u8.nim                alpha_mask_u8.nim
ren agg_arc.nim                          arc.nim
ren agg_arrowhead.nim                    arrowhead.nim
ren agg_basics.nim                       basics.nim
ren agg_bezier_arc.nim                   bezier_arc.nim
ren agg_bitset_iterator.nim              bitset_iterator.nim
ren agg_blur.nim                         blur.nim
ren agg_bounding_rect.nim                bounding_rect.nim
ren agg_bspline.nim                      bspline.nim
ren agg_clip_liang_barsky.nim            clip_liang_barsky.nim
ren agg_color_conv.nim                   color_conv.nim
ren agg_color_conv_rgb16.nim             color_conv_rgb16.nim
ren agg_color_conv_rgb8.nim              color_conv_rgb8.nim
ren agg_color_gray.nim                   color_gray.nim
ren agg_color_rgba.nim                   color_rgba.nim
ren agg_comp_op.nim                      comp_op.nim
ren agg_conv_adaptor_vcgen.nim           conv_adaptor_vcgen.nim
ren agg_conv_adaptor_vpgen.nim           conv_adaptor_vpgen.nim
ren agg_conv_bspline.nim                 conv_bspline.nim
ren agg_conv_clip_polygon.nim            conv_clip_polygon.nim
ren agg_conv_clip_polyline.nim           conv_clip_polyline.nim
ren agg_conv_close_polygon.nim           conv_close_polygon.nim
ren agg_conv_concat.nim                  conv_concat.nim
ren agg_conv_contour.nim                 conv_contour.nim
ren agg_conv_curve.nim                   conv_curve.nim
ren agg_conv_dash.nim                    conv_dash.nim
ren agg_conv_marker.nim                  conv_marker.nim
ren agg_conv_marker_adaptor.nim          conv_marker_adaptor.nim
ren agg_conv_poly_bool.nim               conv_poly_bool.nim
ren agg_conv_segmentator.nim             conv_segmentator.nim
ren agg_conv_shorten_path.nim            conv_shorten_path.nim
ren agg_conv_smooth_poly1.nim            conv_smooth_poly1.nim
ren agg_conv_stroke.nim                  conv_stroke.nim
ren agg_conv_transform.nim               conv_transform.nim
ren agg_conv_unclose_polygon.nim         conv_unclose_polygon.nim
ren agg_curves.nim                       curves.nim
ren agg_dda_line.nim                     dda_line.nim
ren agg_ellipse.nim                      ellipse.nim
ren agg_ellipse_bresenham.nim            ellipse_bresenham.nim
ren agg_embedded_raster_fonts.nim        embedded_raster_fonts.nim
ren agg_font_cache_manager.nim           font_cache_manager.nim
ren agg_font_freetype.nim                font_freetype.nim
ren agg_font_types.nim                   font_types.nim
ren agg_font_win32_tt.nim                font_win32_tt.nim
ren agg_gamma_functions.nim              gamma_functions.nim
ren agg_gamma_lut.nim                    gamma_lut.nim
ren agg_gamma_spline.nim                 gamma_spline.nim
ren agg_glyph_raster_bin.nim             glyph_raster_bin.nim
ren agg_gradient_lut.nim                 gradient_lut.nim
ren agg_gsv_text.nim                     gsv_text.nim
ren agg_image_accessors.nim              image_accessors.nim
ren agg_image_filters.nim                image_filters.nim
ren agg_line_aa_basics.nim               line_aa_basics.nim
ren agg_math.nim                         math.nim
ren agg_math_stroke.nim                  math_stroke.nim
ren agg_path_length.nim                  path_length.nim
ren agg_path_storage.nim                 path_storage.nim
ren agg_path_storage_integer.nim         path_storage_integer.nim
ren agg_pattern_filters_rgba.nim         pattern_filters_rgba.nim
ren agg_pixfmt_amask_adaptor.nim         pixfmt_amask_adaptor.nim
ren agg_pixfmt_gray.nim                  pixfmt_gray.nim
ren agg_pixfmt_rgb.nim                   pixfmt_rgb.nim
ren agg_pixfmt_rgba.nim                  pixfmt_rgba.nim
ren agg_pixfmt_rgb_packed.nim            pixfmt_rgb_packed.nim
ren agg_pixfmt_transposer.nim            pixfmt_transposer.nim
ren agg_rasterizer_cells_aa.nim          rasterizer_cells_aa.nim
ren agg_rasterizer_compound_aa.nim       rasterizer_compound_aa.nim
ren agg_rasterizer_outline.nim           rasterizer_outline.nim
ren agg_rasterizer_outline_aa.nim        rasterizer_outline_aa.nim
ren agg_rasterizer_scanline_aa.nim       rasterizer_scanline_aa.nim
ren agg_rasterizer_sl_clip.nim           rasterizer_sl_clip.nim
ren agg_renderer_base.nim                renderer_base.nim
ren agg_renderer_markers.nim             renderer_markers.nim
ren agg_renderer_mclip.nim               renderer_mclip.nim
ren agg_renderer_outline_aa.nim          renderer_outline_aa.nim
ren agg_renderer_outline_image.nim       renderer_outline_image.nim
ren agg_renderer_primitives.nim          renderer_primitives.nim
ren agg_renderer_raster_text.nim         renderer_raster_text.nim
ren agg_renderer_scanline.nim            renderer_scanline.nim
ren agg_rendering_buffer.nim             rendering_buffer.nim
ren agg_rounded_rect.nim                 rounded_rect.nim
ren agg_scanline_bin.nim                 scanline_bin.nim
ren agg_scanline_boolean_algebra.nim     scanline_boolean_algebra.nim
ren agg_scanline_p.nim                   scanline_p.nim
ren agg_scanline_storage_aa.nim          scanline_storage_aa.nim
ren agg_scanline_storage_bin.nim         scanline_storage_bin.nim
ren agg_scanline_u.nim                   scanline_u.nim
ren agg_shorten_path.nim                 shorten_path.nim
ren agg_simul_eq.nim                     simul_eq.nim
ren agg_span_allocator.nim               span_allocator.nim
ren agg_span_converter.nim               span_converter.nim
ren agg_span_gouraud.nim                 span_gouraud.nim
ren agg_span_gouraud_gray.nim            span_gouraud_gray.nim
ren agg_span_gouraud_rgba.nim            span_gouraud_rgba.nim
ren agg_span_gradient.nim                span_gradient.nim
ren agg_span_gradient_alpha.nim          span_gradient_alpha.nim
ren agg_span_gradient_contour.nim        span_gradient_contour.nim
ren agg_span_gradient_image.nim          span_gradient_image.nim
ren agg_span_image_filter.nim            span_image_filter.nim
ren agg_span_image_filter_gray.nim       span_image_filter_gray.nim
ren agg_span_image_filter_rgb.nim        span_image_filter_rgb.nim
ren agg_span_image_filter_rgba.nim       span_image_filter_rgba.nim
ren agg_span_interpolator_adaptor.nim    span_interpolator_adaptor.nim
ren agg_span_interpolator_linear.nim     span_interpolator_linear.nim
ren agg_span_interpolator_persp.nim      span_interpolator_persp.nim
ren agg_span_interpolator_trans.nim      span_interpolator_trans.nim
ren agg_span_pattern_gray.nim            span_pattern_gray.nim
ren agg_span_pattern_rgb.nim             span_pattern_rgb.nim
ren agg_span_pattern_rgba.nim            span_pattern_rgba.nim
ren agg_span_solid.nim                   span_solid.nim
ren agg_span_subdiv_adaptor.nim          span_subdiv_adaptor.nim
ren agg_trans_affine.nim                 trans_affine.nim
ren agg_trans_bilinear.nim               trans_bilinear.nim
ren agg_trans_double_path.nim            trans_double_path.nim
ren agg_trans_perspective.nim            trans_perspective.nim
ren agg_trans_single_path.nim            trans_single_path.nim
ren agg_trans_viewport.nim               trans_viewport.nim
ren agg_trans_warp_magnifier.nim         trans_warp_magnifier.nim
ren agg_vcgen_bspline.nim                vcgen_bspline.nim
ren agg_vcgen_contour.nim                vcgen_contour.nim
ren agg_vcgen_dash.nim                   vcgen_dash.nim
ren agg_vcgen_markers_term.nim           vcgen_markers_term.nim
ren agg_vcgen_smooth_poly1.nim           vcgen_smooth_poly1.nim
ren agg_vcgen_stroke.nim                 vcgen_stroke.nim
ren agg_vcgen_vertex_sequence.nim        vcgen_vertex_sequence.nim
ren agg_vertex_block_storage.nim         vertex_block_storage.nim
ren agg_vertex_sequence.nim              vertex_sequence.nim
ren agg_vpgen_clip_polygon.nim           vpgen_clip_polygon.nim
ren agg_vpgen_clip_polyline.nim          vpgen_clip_polyline.nim
ren agg_vpgen_segmentator.nim            vpgen_segmentator.nim

